CREATE DATABASE IF NOT EXISTS schedule;
USE schedule;

CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    roles VARCHAR(100) NOT NULL,
    availability JSON NOT NULL
);